<?php

return [
    'sections' => [
        ['title' => 'Overview', 'route' => 'about'],
        ['title' => 'Introduction', 'route' => 'about.introduction'],
        ['title' => 'Group Companies', 'route' => 'about.group-companies'],
        ['title' => 'Company Milestones', 'route' => 'about.company-history'],
        ['title' => 'Certificates', 'route' => 'about.certificates'],
        ['title' => 'Plants & Facilities', 'route' => 'about.plants'],
        ['title' => 'Our Products', 'route' => 'about.products'],
        ['title' => 'Our Customers', 'route' => 'about.customers'],
        ['title' => 'Contact Us', 'route' => 'about.contact'],
    ],
    'pages' => [
        'introduction' => [
            'title' => 'Introduction', 'eyebrow' => 'WHO WE ARE', 'headline' => 'Comfort in every journey.',
            'description' => 'Established in Indonesia in 2007, PT. Fuji Seat Indonesia manufactures automotive seats and interior accessories for PT. Astra Daihatsu Motor (ADM) and PT. Toyota Motor Manufacturing Indonesia (TMMIN).',
            'image' => 'production-assembly.jpg', 'image_alt' => 'Fuji Seat Indonesia team assembling automotive seats',
            'facts' => [['value' => '12 March 2007', 'label' => 'Established in Indonesia'], ['value' => '2,000+', 'label' => 'Seats produced per day'], ['value' => '2,000 approx.', 'label' => 'Employees in 2022']],
            'body_title' => 'A company built around people and ideas',
            'paragraphs' => ['Our company profile describes a production network that serves leading vehicle makers in Indonesia. Teams across our plants combine manufacturing experience, quality focus, and care for every seat.', 'The figures shown here are from the company profile published in 2022.'],
        ],
        'group-companies' => [
            'title' => 'Group Companies', 'eyebrow' => 'ABOUT US', 'headline' => 'Group Companies',
            'description' => 'The Fuji Seat Group spans Japan and overseas operations, working together to deliver high-quality automotive seating and interior components to customers worldwide.',
            'image' => 'plant-exterior.jpg', 'image_alt' => 'Fuji Seat Indonesia Suryacipta manufacturing facility',
            'quote' => 'People, Technology and Manufacturing Creating Better Mobility for Tomorrow',
            'network_sections' => [
                [
                    'title' => 'Fuji Seat Group (Japan)', 'eyebrow' => 'JAPAN OPERATIONS',
                    'description' => 'Our foundation in Japan, with manufacturing plants and a technical center supporting quality and innovation.',
                    'map' => 'group-network-japan.jpg', 'map_alt' => 'Japan map from the Fuji Seat Group company profile',
                    'locations' => [
                        ['name' => 'Futaba Main Plant', 'location' => 'Minoh, Osaka'],
                        ['name' => 'Futaba Sewing', 'location' => 'Hirakata, Osaka'],
                        ['name' => 'Futaba Shiga Plant', 'location' => 'Shiga'],
                        ['name' => 'Futaba Nagasaki Plant', 'location' => 'Sasebo, Nagasaki'],
                        ['name' => 'Futaba Kyushu Plant', 'location' => 'Usa, Oita'],
                        ['name' => 'Futaba Shikoku Plant', 'location' => 'Uwajima, Ehime'],
                        ['name' => 'Fusou Oita Plant', 'location' => 'Nakatsu, Oita'],
                        ['name' => 'FJJ Shiga Plant 1', 'location' => 'Omihachiman, Shiga'],
                        ['name' => 'FJJ Shiga Plant 2', 'location' => 'Higashiomi, Shiga'],
                        ['name' => 'FJJ Kyoto Plant', 'location' => 'Nagaokakyo, Kyoto'],
                        ['name' => 'FJJ Main Plant', 'location' => 'Toyonaka, Osaka'],
                        ['name' => 'Technical Center', 'location' => 'Toyonaka, Osaka'],
                    ],
                ],
                [
                    'title' => 'Fuji Seat Group (Overseas)', 'eyebrow' => 'OVERSEAS OPERATIONS',
                    'description' => 'A regional network across Asia, connecting customers and manufacturing operations.',
                    'map' => 'group-network-asia.jpg', 'map_alt' => 'Asia map from the Fuji Seat Group company profile',
                    'countries' => [
                        ['code' => 'MY', 'title' => 'Malaysia', 'company' => 'FUJI SEATS MALAYSIA SDN. BHD.', 'locations' => [['name' => 'Malaysia Plant', 'location' => 'Rawang, Selangor']]],
                        ['code' => 'ID', 'title' => 'Indonesia', 'company' => 'PT. Fuji Seat Indonesia', 'locations' => [['name' => 'Sunter', 'location' => 'Sunter, Jakarta'], ['name' => 'Karawang Plant', 'location' => 'Karawang Barat'], ['name' => 'Suryacipta 1 Plant', 'location' => 'Karawang Timur'], ['name' => 'Suryacipta 2 Plant', 'location' => 'Karawang Timur']]],
                        ['code' => 'CN', 'title' => 'China', 'company' => 'Fuji Seat Group', 'locations' => [['name' => 'Futaba Shanghai', 'location' => 'Fengxian, Shanghai'], ['name' => 'Wuhan Fubo Plant', 'location' => 'Wuhan, Hubei']]],
                        ['code' => 'VN', 'title' => 'Vietnam', 'company' => 'Futaba Vietnam', 'locations' => [['name' => 'Futaba Vietnam', 'location' => 'Vinh Phuc, Hanoi']]],
                    ],
                ],
            ],
        ],
        'milestones' => [
            'title' => 'Company Milestones', 'eyebrow' => 'OUR JOURNEY', 'headline' => 'Built through steady progress.',
            'description' => 'From our early beginnings in 2005 to new production lines in 2024, each milestone reflects the growth of our people, plants, and customer programs.',
            'image' => 'plant-exterior.jpg', 'image_alt' => 'Fuji Seat Indonesia manufacturing facility',
            'quote' => 'Growing Together for a Better Tomorrow',
            'note' => 'The company profile notes PT. Fuji Seat Indonesia was established on 12 March 2007. Fuji Meiwa, an earlier predecessor, began in Depok in November 2005.',
            'milestone_cards' => [
                ['year' => '2005', 'title' => 'Establish Fuji Meiwa', 'text' => 'Fuji Meiwa was established in Depok. Xenia and Avanza mass production began in November.', 'image' => 'hero-sunter.jpg', 'alt' => 'Fuji Seat Indonesia plant facility from the company profile'],
                ['year' => '2007', 'title' => 'Establish Sunter Plant', 'text' => 'Fuji Seat Indonesia established its Sunter plant in March; Gran Max production began in November.', 'image' => 'hero-sunter.jpg', 'alt' => 'Sunter plant facility'],
                ['year' => '2009', 'title' => 'Merger with Fuji Meiwa', 'text' => 'Luxio mass production began in January, followed by the Fuji Seat Indonesia and Fuji Meiwa merger in August.', 'image' => 'production-team.jpg', 'alt' => 'Fuji Seat Indonesia employees at work'],
                ['year' => '2011', 'title' => 'Establish KIIC Plant', 'text' => 'The KIIC plant opened in June; the D01N Xenia and Avanza program followed in November.', 'image' => 'hero-kiic.jpg', 'alt' => 'KIIC plant facility'],
                ['year' => '2016', 'title' => 'Establish Suryacipta 1', 'text' => 'The plant opened in January, followed by Sigra and Calya mass production in July.', 'image' => 'hero-suryacipta-1.jpg', 'alt' => 'Suryacipta 1 plant facility'],
                ['year' => '2018', 'title' => 'Establish Suryacipta 2', 'text' => 'Fuji Seat Indonesia established its second Suryacipta plant in February.', 'image' => 'hero-suryacipta-2.jpg', 'alt' => 'Suryacipta 2 plant facility'],
                ['year' => '2019', 'title' => 'Establish Assy KIIC Plant', 'text' => 'The Assy KIIC plant opened in June; D30D (Calya) mass production began in November.', 'image' => 'hero-kiic.jpg', 'alt' => 'KIIC plant facility'],
                ['year' => '2021', 'title' => 'New Vehicle Programs', 'text' => 'Rocky and Raize began production in March; new Avanza and Xenia, and DCWA (Kozui), followed in November.', 'image' => 'vehicle-rocky.jpg', 'alt' => 'Rocky vehicle from the company profile lineup'],
                ['year' => '2023', 'title' => 'New Ayla / Agya', 'text' => 'The new Ayla and Agya entered mass production in September.', 'image' => 'vehicle-ayla.jpg', 'alt' => 'Ayla vehicle from the company profile lineup'],
                ['year' => '2024', 'title' => 'SC-1 Line Assy-2', 'text' => 'Fuji Seat Indonesia established SC-1 Line Assy-2 in December to expand production capacity.', 'image' => 'production-assembly.jpg', 'alt' => 'Automotive seat assembly production line'],
            ],
            'product_milestones' => [
                ['name' => 'Gran Max', 'detail' => 'Mass production · 2007', 'image' => 'vehicle-granmax.jpg', 'alt' => 'Gran Max vehicle from the company profile'],
                ['name' => 'Luxio', 'detail' => 'Mass production · 2009', 'image' => 'vehicle-luxio.jpg', 'alt' => 'Luxio vehicle from the company profile'],
                ['name' => 'New Ayla / Agya', 'detail' => 'New generation · 2023', 'image' => 'vehicle-ayla.jpg', 'alt' => 'Ayla vehicle from the company profile'],
                ['name' => 'Sigra / Calya', 'detail' => 'Mass production · 2016', 'image' => 'product-8.jpg', 'alt' => 'Sigra and Calya seat assemblies from the company profile'],
                ['name' => 'Kozui', 'detail' => 'DCWA · 2021 / D25B · 2022', 'image' => 'seat-program-latest-01.jpg', 'alt' => 'Automotive seat assembly from the company profile'],
            ],
        ],
        'certificates' => [
            'title' => 'Certificates', 'eyebrow' => 'QUALITY & RESPONSIBILITY', 'headline' => 'Standards we work to uphold.',
            'description' => 'The company profile presents quality management, environmental responsibility, occupational safety, and operational performance records.',
            'image' => 'production-assembly.jpg', 'image_alt' => 'Automotive seat assembly at Fuji Seat Indonesia',
            'cards' => [
                ['title' => 'ISO 14001:2015', 'text' => 'Environmental management system certificate shown in the 2021 profile.', 'image' => 'certificate-iso14001.jpg', 'alt' => 'ISO 14001 certificate shown in the company profile'],
                ['title' => 'ISO 9001:2015', 'text' => 'Quality management system certificate shown in the 2022 profile.', 'image' => 'certificate-iso9001.jpg', 'alt' => 'ISO 9001 certificate shown in the company profile'],
                ['title' => 'PROPER Blue', 'text' => 'Environmental performance rating for the 2022–2023 period.', 'image' => 'certificate-proper-blue.jpg', 'alt' => 'Ministry of Environment PROPER Blue rating certificate'],
                ['title' => 'SMK3 Audit', 'text' => 'Occupational safety and health management audit report from December 2023.', 'image' => 'certificate-smk3.jpg', 'alt' => 'SMK3 occupational safety audit report'],
                ['title' => 'Zero Accident Award', 'text' => 'KIIC plant recognition for the 1 January 2015–31 December 2022 period, awarded in 2023.', 'image' => 'certificate-zero-accident.jpg', 'alt' => 'Zero Accident Award certificate for KIIC plant'],
            ],
            'note' => 'These are records reproduced from the company profile. Certificate periods are historical and do not indicate current validity.',
        ],
        'plants' => [
            'title' => 'Plants & Facilities', 'eyebrow' => 'OUR INDONESIAN OPERATIONS', 'headline' => 'Four plants. One quality commitment.',
            'description' => 'Our facilities in Sunter, KIIC, and Suryacipta support seat assembly and specialized manufacturing processes across the production chain.',
            'image' => 'plant-exterior.jpg', 'image_alt' => 'Fuji Seat Indonesia manufacturing plant',
            'showcase_description' => 'PT. Fuji Seat Indonesia operates a strategic manufacturing network across Jakarta and Karawang, equipped with advanced facilities, integrated processes, and a dedicated workforce to deliver high-quality automotive seating and components for global customers.',
            'featured_plants' => [
                ['title' => 'Sunter Plant', 'location' => 'Jakarta', 'roles' => ['Head Office', 'Seat Assembly'], 'building_area' => '5,500', 'surface_area' => '9,738', 'image' => 'plant-profile-sunter.jpg', 'alt' => 'Sunter head office and plant from the company profile', 'capabilities' => ['assembling']],
                ['title' => 'KIIC Plant', 'location' => 'Karawang', 'roles' => ['Part Mother Plant', 'Seat Assembly'], 'building_area' => '19,380', 'surface_area' => '46,570', 'image' => 'plant-profile-kiic.jpg', 'alt' => 'KIIC manufacturing facility from the company profile', 'capabilities' => ['assembling', 'stamping', 'injection', 'welding', 'urethane']],
                ['title' => 'Surya Cipta-1 Plant', 'location' => 'Karawang', 'roles' => ['Seat Assembly', 'Urethane Happo'], 'building_area' => '10,100', 'surface_area' => '73,459', 'image' => 'plant-profile-suryacipta-1.jpg', 'alt' => 'Surya Cipta-1 plant exterior from the company profile', 'capabilities' => ['assembling', 'urethane']],
                ['title' => 'Surya Cipta-2 Plant', 'location' => 'Karawang', 'roles' => ['Cover Sewing', 'Saidan, Headrest Happo'], 'building_area' => '11,670', 'surface_area' => '32,541', 'image' => 'plant-profile-suryacipta-2.jpg', 'alt' => 'Surya Cipta-2 plant exterior from the company profile', 'capabilities' => ['sewing', 'headrest']],
            ],
            'capabilities' => [
                'assembling' => 'Assembling', 'stamping' => 'Stamping', 'injection' => 'Injection', 'welding' => 'Welding', 'urethane' => 'Urethane', 'sewing' => 'Sewing & Saidan', 'headrest' => 'Headrest / Happo',
            ],
            'quality_facilities' => [
                ['title' => 'Accuracy Tools', 'description' => 'Coordinate measuring, profile and precision measuring equipment support dimensional accuracy.', 'image' => 'facility-accuracy-tools.jpg', 'alt' => 'Precision measuring equipment from the company profile'],
                ['title' => 'Product Guarantee Tools', 'description' => 'Seat and frame durability equipment helps verify product performance and long-lasting quality.', 'image' => 'facility-product-guarantee.jpg', 'alt' => 'Seat durability testing equipment from the company profile'],
                ['title' => 'Testing Facility', 'description' => 'Strength, durability, safety, and material testing support automotive quality standards.', 'image' => 'facility-testing.jpg', 'alt' => 'Seat frame testing equipment from the company profile'],
            ],
            'cards' => [
                ['title' => 'Sunter', 'text' => 'Head office and seat assembly. The profile records 5,500 m² of building area on a 9,738 m² site.', 'image' => 'hero-sunter.jpg', 'alt' => 'Sunter head office and plant'],
                ['title' => 'KIIC', 'text' => 'Parts mother plant and seat assembly. 19,380 m² of building area on a 46,570 m² site.', 'image' => 'hero-kiic.jpg', 'alt' => 'KIIC manufacturing facility'],
                ['title' => 'Suryacipta 1', 'text' => 'Seat assembly and urethane production. 10,100 m² of building area on a 73,459 m² site.', 'image' => 'plant-exterior.jpg', 'alt' => 'Suryacipta 1 plant exterior'],
                ['title' => 'Suryacipta 2', 'text' => 'Cover sewing, saidan, and headrest/happo operations. 11,670 m² of building area on a 32,541 m² site.', 'image' => 'plant-suryacipta-2.jpg', 'alt' => 'Suryacipta 2 plant exterior'],
            ],
            'body_title' => 'Capabilities across the production chain',
            'paragraphs' => ['The company profile lists stamping, welding, injection, urethane, sewing, saidan, headrest/happo, and seat assembly capabilities across its Indonesian facilities.', 'It also documents inspection and test equipment, including coordinate measurement, surface and color measurement, seat durability, frame durability, flammability, and strength testing.'],
        ],
        'products' => [
            'title' => 'Our Products', 'eyebrow' => 'OUR PRODUCTS', 'headline' => 'Our Products',
            'description' => 'Automotive seats and interior components for a wide range of vehicles, combining comfort, safety, and quality for a better driving experience.',
            'image' => 'seat-interior.jpg', 'image_alt' => 'Automotive seats produced by Fuji Seat Indonesia',
            'quote' => 'Seats and interior components that move people towards a better tomorrow',
            'vehicle_heading' => 'Our Products for Various Vehicle Models',
            'vehicle_intro' => 'Seat programs developed for passenger, multipurpose, and commercial vehicles.',
            'cards' => [
                ['title' => 'Xenia / Avanza / Veloz', 'text' => 'Passenger vehicles', 'image' => 'vehicle-xenia.jpg', 'alt' => 'Xenia from the vehicle lineup in the company profile'],
                ['title' => 'Terios / Rush', 'text' => 'Passenger vehicles', 'image' => 'vehicle-terios.jpg', 'alt' => 'Terios from the vehicle lineup in the company profile'],
                ['title' => 'Rocky / Raize', 'text' => 'Passenger vehicles', 'image' => 'vehicle-rocky.jpg', 'alt' => 'Rocky from the vehicle lineup in the company profile'],
                ['title' => 'Sigra / Calya', 'text' => 'Passenger vehicles', 'image' => 'product-8.jpg', 'alt' => 'Seat assembly for the Sigra and Calya vehicle program'],
                ['title' => 'Ayla / Agya', 'text' => 'Passenger vehicles', 'image' => 'vehicle-ayla.jpg', 'alt' => 'Ayla from the vehicle lineup in the company profile'],
                ['title' => 'Gran Max', 'text' => 'Commercial vehicle', 'image' => 'vehicle-granmax.jpg', 'alt' => 'Gran Max from the vehicle lineup in the company profile'],
                ['title' => 'Luxio', 'text' => 'Multipurpose vehicle', 'image' => 'vehicle-luxio.jpg', 'alt' => 'Luxio from the vehicle lineup in the company profile'],
            ],
            'seat_heading' => 'Seat Assembly for Comfort and Quality',
            'seat_intro' => 'Complete seat assembly solutions designed for each vehicle model, delivering comfort, functionality, and reliability.',
            'seat_assemblies' => [
                ['title' => 'Xenia / Avanza / Veloz', 'image' => 'product-2.jpg', 'alt' => 'Fuji Seat assembly for passenger vehicle programs'],
                ['title' => 'Terios / Rush', 'image' => 'product-5.jpg', 'alt' => 'Fuji Seat assembly for Terios and Rush programs'],
                ['title' => 'Rocky / Raize', 'image' => 'product-6.jpg', 'alt' => 'Fuji Seat assembly for Rocky and Raize programs'],
                ['title' => 'Sigra / Calya', 'image' => 'product-8.jpg', 'alt' => 'Fuji Seat assembly for Sigra and Calya programs'],
                ['title' => 'Ayla / Agya', 'image' => 'product-7.jpg', 'alt' => 'Fuji Seat assembly for Ayla and Agya programs'],
                ['title' => 'Gran Max', 'image' => 'product-4.jpg', 'alt' => 'Fuji Seat assembly for Gran Max'],
                ['title' => 'Luxio', 'image' => 'product-3.jpg', 'alt' => 'Fuji Seat assembly for Luxio'],
            ],
            'parts_heading' => 'Single / Assy Parts',
            'parts_intro' => 'Interior and structural components manufactured with precision for durability, safety, and design flexibility.',
            'parts' => [
                ['title' => 'Injection Parts', 'text' => 'Interior plastic components with excellent durability and finish.', 'image' => 'components-interior.jpg', 'alt' => 'Moulded automotive interior plastic components'],
                ['title' => 'Stamping Parts', 'text' => 'Structural metal components made with precision.', 'image' => 'component-stamping.jpg', 'alt' => 'Stamped metal automotive seat components from the company profile'],
                ['title' => 'Urethane Parts', 'text' => 'Comfort-focused cushioning components for automotive seating.', 'image' => 'components-foam.jpg', 'alt' => 'Urethane foam components for automotive seats'],
                ['title' => 'Welding Parts', 'text' => 'Reliable welded structures for strength and safety.', 'image' => 'component-welded-frame.jpg', 'alt' => 'Welded automotive seat frame from the company profile'],
                ['title' => 'Headrest / Sewing Parts', 'text' => 'Headrests and sewn components with refined fit and finish.', 'image' => 'component-headrest-sewing.jpg', 'alt' => 'Automotive headrest and seat fabric component from the company profile'],
            ],
        ],
        'customers' => [
            'title' => 'Our Customers', 'eyebrow' => 'TRUSTED PARTNERSHIPS', 'headline' => 'Supporting Indonesia’s automotive leaders.',
            'description' => 'PT. Fuji Seat Indonesia produces automotive seats for two leading vehicle manufacturers in Indonesia.',
            'image' => 'production-team.jpg', 'image_alt' => 'Fuji Seat Indonesia production team supporting customer programs',
            'cards' => [
                ['title' => 'PT. Astra Daihatsu Motor', 'text' => 'ADM', 'image' => 'customer-daihatsu.jpg', 'alt' => 'Daihatsu logo'],
                ['title' => 'PT. Toyota Motor Manufacturing Indonesia', 'text' => 'TMMIN', 'image' => 'customer-toyota.jpg', 'alt' => 'Toyota logo'],
            ],
        ],
        'contact' => [
            'title' => 'Contact Us', 'eyebrow' => 'GET IN TOUCH', 'headline' => 'Let’s build a better journey.',
            'description' => 'Reach the Fuji Seat Indonesia plant that best fits your inquiry.', 'image' => 'hero-sunter.jpg', 'image_alt' => 'Fuji Seat Indonesia Sunter facility',
            'offices' => [
                ['title' => 'Head Office & Sunter Plant', 'address' => 'Jl. Agung Perkasa IX, Blok K.1 Kav. 9–15, Sunter, Jakarta Utara', 'phone' => '+62 21 6530 2228', 'fax' => '+62 21 6530 3486'],
                ['title' => 'KIIC Plant', 'address' => 'Jl. Maligi VIII, Lot S No. 6, Kawasan KIIC, Karawang Barat', 'phone' => '+62 267 8631 761', 'fax' => '+62 267 8631 763'],
                ['title' => 'Suryacipta 1 Plant', 'address' => 'Jl. Surya Madya IV, Kav. I-30 ABC, Kawasan Suryacipta, Karawang Timur, Jawa Barat', 'phone' => '+62 267 8404 007', 'fax' => '+62 267 8404 009'],
                ['title' => 'Suryacipta 2 Plant', 'address' => 'Jl. Surya Pratama, Kav. I-64, Kawasan Suryacipta, Karawang Timur, Jawa Barat', 'phone' => '+62 267 8404 118', 'fax' => '+62 267 8408 117'],
            ],
        ],
    ],
];
