<?php

return [
    'company' => 'PT. Fuji Seat Indonesia',
    'tagline' => 'Never standing still, always evolving',
    'description' => 'PT. FUJI SEAT INDONESIA is a foreign company producing car-seats for PT. ASTRA DAIHATSU MOTOR (ADM) and PT. TOYOTA MOTOR MANUFACTURING INDONESIA (TMMIN) as a leading automotive company in Indonesia, with a production capacity of more than 2000 seats per day and employing about 2000 workers (2022).',
    'slides' => [
        ['title' => 'HEAD OFFICE - SUNTER PLANT', 'image' => 'hero-sunter.jpg', 'width' => 1400, 'height' => 827],
        ['title' => 'KARAWANG - KIIC PLANT', 'image' => 'hero-kiic.jpg', 'width' => 1400, 'height' => 827],
        ['title' => 'KARAWANG - SURYACIPTA PLANT 1', 'image' => 'plant-exterior.jpg', 'width' => 1862, 'height' => 806],
        ['title' => 'KARAWANG - SURYACIPTA PLANT 2', 'image' => 'plant-suryacipta-2.jpg', 'width' => 1897, 'height' => 930],
    ],
    'products' => [
        ['name' => 'Xenia', 'detail' => 'First production: November 2005. New generation: November 2021.', 'image' => 'product-1.jpg', 'rotationSprite' => 'seat-360-sprite.png'],
        ['name' => 'Avanza', 'detail' => 'First production: November 2005. New generation: November 2021.', 'image' => 'product-2.jpg', 'rotationSprite' => 'seat-360-sprite.png'],
        ['name' => 'Terios', 'detail' => 'First production: November 2006. New generation: December 2017.', 'image' => 'product-5.jpg', 'rotationSprite' => 'seat-360-terios-2006.png'],
        ['name' => 'Rush', 'detail' => 'First production: November 2006. New generation: December 2017.', 'image' => 'product-6.jpg', 'rotationSprite' => 'seat-360-rush-2006.png'],
        ['name' => 'Gran Max', 'detail' => 'November 2007, GRAN MAX Start Mass Production', 'image' => 'product-4.jpg', 'rotationSprite' => 'seat-360-sprite.png'],
        ['name' => 'Luxio', 'detail' => 'January 2009, LUXIO Start Mass Production', 'image' => 'product-3.jpg', 'rotationSprite' => 'seat-360-sprite.png'],
        ['name' => 'Ayla & Agya', 'detail' => 'First production: December 2013. New generation: September 2023.', 'image' => 'product-7.jpg', 'rotationSprite' => 'seat-360-ayla-agya.png'],
        ['name' => 'Calya & Sigra', 'detail' => 'First production: July 2016. New Calya program: November 2019.', 'image' => 'product-8.jpg', 'rotationSprite' => 'seat-360-calya.png'],
        ['name' => '2017 - New Terios / Rush', 'year' => 2017, 'detail' => 'Seat assembly for the New Terios and Rush vehicle program.', 'description' => 'Seat assembly for the New Terios and Rush vehicle program.', 'massProduction' => '2017', 'vehicleType' => 'Passenger SUV', 'company' => 'Fuji Seat Indonesia', 'productionStatus' => 'Mass production', 'image' => 'showcase-terios-rush-reference.png', 'thumbnail' => 'showcase-terios-rush-reference.png', 'alt' => '2017 New Terios and Rush seats: FR, RR1, and RR2', 'width' => 1672, 'height' => 941, 'rotationSprite' => 'seat-360-terios-rush-2017.png'],
        ['name' => '2019 - Calya', 'year' => 2019, 'detail' => 'Brown seat assembly for the Calya vehicle program.', 'description' => 'Brown seat assembly for the Calya vehicle program.', 'massProduction' => '2019', 'vehicleType' => 'Passenger MPV', 'company' => 'Fuji Seat Indonesia', 'productionStatus' => 'Mass production', 'image' => 'showcase-calya-reference.png', 'thumbnail' => 'showcase-calya-reference.png', 'alt' => '2019 Calya brown seats: FR, RR1, and RR2', 'width' => 1672, 'height' => 941, 'rotationSprite' => 'seat-360-calya.png'],
        ['name' => '2021 - Rocky / Raize', 'year' => 2021, 'detail' => 'Patterned seat assembly for the Rocky and Raize vehicle program.', 'description' => 'Patterned seat assembly for the Rocky and Raize vehicle program.', 'massProduction' => '2021', 'vehicleType' => 'Passenger SUV', 'company' => 'Fuji Seat Indonesia', 'productionStatus' => 'Mass production', 'image' => 'showcase-rocky-raize-reference.png', 'thumbnail' => 'showcase-rocky-raize-reference.png', 'alt' => '2021 Rocky and Raize patterned seats: FR, RR1, and RR2', 'width' => 1672, 'height' => 940, 'rotationSprite' => 'seat-360-rocky-raize.png'],
        ['name' => '2021 - New Avanza / Xenia', 'year' => 2021, 'detail' => 'Patterned seat assembly for the New Avanza and Xenia vehicle program.', 'description' => 'Patterned seat assembly for the New Avanza and Xenia vehicle program.', 'massProduction' => '2021', 'vehicleType' => 'Passenger MPV', 'company' => 'Fuji Seat Indonesia', 'productionStatus' => 'Mass production', 'image' => 'showcase-avanza-xenia-reference.png', 'thumbnail' => 'showcase-avanza-xenia-reference.png', 'alt' => '2021 New Avanza and Xenia patterned seats: FR, RR1, and RR2', 'width' => 1672, 'height' => 941, 'rotationSprite' => 'seat-360-avanza-xenia.png'],
        ['name' => '2023 - New Ayla / Agya', 'year' => 2023, 'detail' => 'Quilted seat assembly for the New Ayla and Agya vehicle program.', 'description' => 'Quilted seat assembly for the New Ayla and Agya vehicle program.', 'massProduction' => '2023', 'vehicleType' => 'Passenger hatchback', 'company' => 'Fuji Seat Indonesia', 'productionStatus' => 'Mass production', 'image' => 'showcase-ayla-agya-reference.png', 'thumbnail' => 'showcase-ayla-agya-reference.png', 'alt' => '2023 New Ayla and Agya quilted seats: FR, RR1, and RR2', 'width' => 1672, 'height' => 941, 'rotationSprite' => 'seat-360-ayla-agya.png'],
    ],
    'product_lineup' => [
        ['name' => 'Xenia / Avanza / Veloz', 'year' => '2005', 'detail' => 'The original Xenia and Avanza program began in November 2005; the new generation entered mass production in November 2021.', 'image' => 'vehicle-xenia.jpg', 'vehicle_type' => 'passenger'],
        ['name' => 'Terios / Rush', 'year' => '2006', 'detail' => 'Terios and Rush entered mass production in November 2006. A new generation followed in December 2017.', 'image' => 'vehicle-terios.jpg', 'vehicle_type' => 'passenger'],
        ['name' => 'Gran Max', 'year' => '2007', 'detail' => 'Gran Max entered mass production in November 2007.', 'image' => 'vehicle-granmax.jpg', 'vehicle_type' => 'commercial'],
        ['name' => 'Luxio', 'year' => '2009', 'detail' => 'Luxio entered mass production in January 2009.', 'image' => 'vehicle-luxio.jpg', 'vehicle_type' => 'commercial'],
        ['name' => 'Ayla / Agya', 'year' => '2013', 'detail' => 'The original program began in December 2013; the new Ayla and Agya entered mass production in September 2023.', 'image' => 'vehicle-ayla.jpg', 'vehicle_type' => 'passenger'],
        ['name' => 'Sigra / Calya', 'year' => '2016', 'detail' => 'Sigra and Calya entered mass production in July 2016; the D30D Calya program followed in November 2019.', 'image' => 'product-8.jpg', 'vehicle_type' => 'passenger'],
        ['name' => 'Rocky / Raize', 'year' => '2021', 'detail' => 'Rocky and Raize entered mass production in March 2021.', 'image' => 'vehicle-rocky.jpg', 'vehicle_type' => 'passenger'],
    ],
    'history' => [
        ['year' => '2005', 'events' => ['November, Establish Fuji Meiwa in Depok', 'XENIA & AVANZA Start Mass Production']],
        ['year' => '2006', 'events' => ['November, TERIOS & RUSH Start Mass Production']],
        ['year' => '2007', 'events' => ['March, Establish Fuji Seat Indonesia Sunter Plant', 'November, GRAN MAX Start Mass Production']],
        ['year' => '2009', 'events' => ['January, LUXIO Start Mass Production', 'August, Fuji Seat Indonesia merge Fuji Meiwa']],
        ['year' => '2011', 'events' => ['June, Establish Fuji Seat Indonesia Karawang Plant', 'November, D01N Xenia & Avanza Start Mass Production']],
        ['year' => '2013', 'events' => ['December, AYLA AGYA Start Mass Production']],
        ['year' => '2016', 'events' => ['January, Establish Fuji Seat Indonesia Surya Cipta 1 Plant', 'July, SIGRA & CALYA Start Mass Production']],
        ['year' => '2017', 'events' => ['December, NEW RUSH & TERIOS Start Mass Production']],
        ['year' => '2018', 'events' => ['February, Establish Fuji Seat Indonesia Surya Cipta 2 Plant']],
        ['year' => '2019', 'events' => ['June, Establish Assy KIIC Plant', 'November, Masspro D30D (CALYA)']],
        ['year' => '2021', 'events' => ['March, ROCKY & RAIZE Start Mass Production', 'November, Masspro DCWA (KOZUI)', 'November, NEW AVANZA & XENIA Mass Production']],
        ['year' => '2022', 'events' => ['October, Masspro D25B (KOZUI)']],
        ['year' => '2023', 'events' => ['September, NEW AYLA/AGYA Mass Production']],
        ['year' => '2024', 'events' => ['December, Establish Fuji Seat Indonesia SC-1 Line Assy-2']],
    ],
    'processes' => [
        ['name' => 'Stamping', 'detail' => 'Forming metal parts with dedicated press equipment.', 'image' => 'process-stamping.jpg', 'alt' => 'Large metal stamping presses at the Fuji Seat production facility', 'width' => 2012, 'height' => 980],
        ['name' => 'Welding', 'detail' => 'Joining metal components with robotic welding equipment.', 'image' => 'process-welding.jpg', 'alt' => 'Robotic welding equipment joining metal parts', 'width' => 1027, 'height' => 803],
        ['name' => 'Assembly', 'detail' => 'Bringing seat components together on the production line.', 'image' => 'process-assembly.jpg', 'alt' => 'Fuji Seat employees assembling automotive seats', 'width' => 2045, 'height' => 1268],
    ],
    'components' => [
        ['name' => 'Metal components', 'detail' => 'Formed brackets and structural metal parts.', 'image' => 'components-metal.jpg', 'alt' => 'A selection of stamped metal brackets and structural parts', 'width' => 1447, 'height' => 981],
        ['name' => 'Interior components', 'detail' => 'Moulded covers and interior trim parts.', 'image' => 'components-interior.jpg', 'alt' => 'Black moulded plastic covers and automotive interior trim', 'width' => 986, 'height' => 460],
        ['name' => 'Seat cushioning', 'detail' => 'Shaped foam for automotive seating.', 'image' => 'components-foam.jpg', 'alt' => 'Shaped foam cushioning for an automotive seat', 'width' => 1129, 'height' => 839],
        ['name' => 'Seat frames', 'detail' => 'Metal frames that support the seat structure.', 'image' => 'components-frame.jpg', 'alt' => 'An automotive seat frame with metal springs', 'width' => 491, 'height' => 805],
    ],
    'product_categories' => [
        ['name' => 'Seat Assy', 'detail' => 'Complete seating assemblies for various vehicle models.', 'image' => 'product-1.jpg', 'alt' => 'Complete automotive seat assemblies', 'width' => 350, 'height' => 280, 'filters' => 'seat-assy'],
        ['name' => 'Injection Parts', 'detail' => 'Interior plastic components with precise manufacturing quality.', 'image' => 'components-interior.jpg', 'alt' => 'Moulded plastic covers and automotive interior trim', 'width' => 986, 'height' => 460, 'filters' => 'components interior'],
        ['name' => 'Urethane Parts', 'detail' => 'Comfort-focused cushioning components with reliable quality.', 'image' => 'components-foam.jpg', 'alt' => 'Shaped urethane foam for automotive seat cushioning', 'width' => 1129, 'height' => 839, 'filters' => 'components interior'],
        ['name' => 'Welding / Stamping / Headrest & Sewing Parts', 'detail' => 'Structural frames, stamped metal, headrests, and sewing components for automotive seating systems.', 'image' => 'component-headrest-sewing.jpg', 'alt' => 'Automotive headrests and sewn seat upholstery components', 'width' => 1200, 'height' => 800, 'filters' => 'components'],
    ],
    'quality_policy' => [
        'Menghasilkan produk bermutu tinggi sesuai persyaratan pelanggan dan Peraturan Pemerintah yang terkait.',
        'Meningkatkan kepedulian seluruh pekerja terhadap kebijakan mutu dan mengkomunikasikan ke pihak berkepentingan.',
        'Mengembangkan produk, teknologi, pelayanan dan fasilitas untuk mendukung tercapainya sasaran mutu perusahaan.',
        'Mematuhi peraturan dan persyaratan yang berlaku.',
        'Melakukan upaya perbaikan secara berkesinambungan dalam rangka peningakatan kinerja Sistem Manajemen Mutu.',
    ],
    'environment_policy' => [
        'Meningkatkan kepedulian seluruh karyawan terhadap kebijakan lingkungan dan mengkomunikasikan ke pihak berkepentingan.',
        'Mematuhi peraturan perundangan lingkungan dan persyaratan lainnya yang berlaku.',
        'Melakukan efisiensi penggunaan sumber daya alam maupun energi yang digunakan.',
        'Mengembangkan produk, teknologi, pelayanan, dan fasilitas yang ramah lingkungan.',
        'Melindungi lingkungan melalui upaya pengurangan limbah dan mencegah terjadinya pencemaran.',
        'Melakukan upaya perbaikan secara berkesinambungan dalam rangka peningkatan kinerja Sistem Manajemen Lingkungan.',
    ],
    'offices' => [
        ['name' => 'HEAD OFFICE & SUNTER PLANT', 'image' => 'hero-sunter.jpg', 'width' => 1400, 'height' => 827, 'address' => 'Jl. Agung Perkasa IX Blok K.1 Kav 9-15, Sunter, Jakarta Utara', 'telephone' => '(62-21) 6530-2228', 'map' => 'https://goo.gl/maps/gSQMKziQxssdGJP36'],
        ['name' => 'Karawang KIIC Plant', 'image' => 'hero-kiic.jpg', 'width' => 1400, 'height' => 827, 'address' => 'Jl. Maligi VIII Lot S No. 6, Kawasan KIIC, Karawang Barat', 'telephone' => '(62-267) 8631-761', 'map' => 'https://goo.gl/maps/o5YMF8VBqfUPiQ9cA'],
        ['name' => 'Karawang Suryacipta 1 Plant', 'image' => 'plant-exterior.jpg', 'width' => 1862, 'height' => 806, 'address' => 'Jl. Surya Madya IV Kav I-30 ABC, Kawasan Suryacipta, Karawang Timur, Jawa Barat', 'telephone' => '(62-267) 8404-007', 'map' => 'https://goo.gl/maps/n7hrL1BAQHGLu2Cb7'],
        ['name' => 'Karawang Suryacipta 2 Plant', 'image' => 'plant-suryacipta-2.jpg', 'width' => 1897, 'height' => 930, 'address' => 'Jl. Surya Pratama Kav I-64, Kawasan Suryacipta, Karawang Timur, Jawa Barat', 'telephone' => '(62-267) 8404-118', 'map' => 'https://goo.gl/maps/ry1GD7MzZcKkZyHH9'],
    ],
];
